version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
    #need separate build step to accept calls from contentful webhook


    deploy:
        docker:
            - image: circleci/node:lts

        working_directory: ~/repo

        steps:
            - attach_workspace:
                at: ~/repo

            - run:
                name: Install aws cli
                command: sudo apt-get -y -qq install awscli

            - run:
                name: Deploy to S3
                command: aws s3 sync public s3://goodnight-margaret.ianplumb.uk --delete

            - slack/status:
                webhook: ${SLACK_WEBHOOK}
#            - run:
#                name: Enable preview
#                command: aws configure set preview.cloudfront true

#                name: Invalidate
#            - run:
#                command: aws cloudfront create-invalidation --distribution-id EMIX0KMQZU09H --paths /*



    build:
        docker:
            - image: circleci/node:lts

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                keys:
                - v7-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v7-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v7-dependencies-{{ checksum "package.json" }}

            # run tests!
            # - run:
            #    name: Test
            #    command: yarn test

            - run:
                name: Build
                command: yarn build

            - run:
                name: Install aws cli
                command: sudo apt-get -y -qq install awscli

            - run:
                name: Deploy main to S3
                command: aws s3 sync public s3://goodnight-margaret.ianplumb.uk --delete
            - run:
                command: slack notify --webhook ${SLACK_WEBHOOK}


    build-only:
        docker:
            - image: circleci/node:lts

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                keys:
                - v7-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v7-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v7-dependencies-{{ checksum "package.json" }}

            # run tests!
            # - run:
            #    name: Test
            #    command: yarn test

            - run:
                name: Build
                command: yarn build

            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
            # taken to be the root directory of the workspace.
                root: .
                # Must be relative path from root
                paths:
                    - public


    deploy-dev:
        docker:
            - image: circleci/node:lts

        working_directory: ~/repo

        steps:
            - attach_workspace:
                at: ~/repo

            - run:
                name: Install aws cli
                command: sudo apt-get -y -qq install awscli

            - run:
                name: Deploy dev to S3
                command: aws s3 sync public s3://goodnight-margaret.ianplumb.uk --delete

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          context: AWS
          filters:
            branches:
              only:
                - master
          requires:
            - build-only

      - deploy-dev:
          context: AWS
          requires:
            - build-only
          filters:
            branches:
              ignore: master
      - build-only:
          context: AWS
